// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2vZtBTJMBSdeGMBROSxZuzjCWZW9qLuU',
    appId: '1:673634726484:web:762473efbf0b067ea373c1',
    messagingSenderId: '673634726484',
    projectId: 'todoapp202661',
    authDomain: 'todoapp202661.firebaseapp.com',
    storageBucket: 'todoapp202661.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVq2_eV7r9IUv4zJWKTIzkA9ta6rnQQFU',
    appId: '1:673634726484:android:e96ab5917824cd2ca373c1',
    messagingSenderId: '673634726484',
    projectId: 'todoapp202661',
    storageBucket: 'todoapp202661.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoTQJfDCzaR-wntDdr1InjZXJUKoZ5ewU',
    appId: '1:673634726484:ios:b27066026ee0d1fca373c1',
    messagingSenderId: '673634726484',
    projectId: 'todoapp202661',
    storageBucket: 'todoapp202661.firebasestorage.app',
    iosBundleId: 'com.example.getxExamples',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoTQJfDCzaR-wntDdr1InjZXJUKoZ5ewU',
    appId: '1:673634726484:ios:b27066026ee0d1fca373c1',
    messagingSenderId: '673634726484',
    projectId: 'todoapp202661',
    storageBucket: 'todoapp202661.firebasestorage.app',
    iosBundleId: 'com.example.getxExamples',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2vZtBTJMBSdeGMBROSxZuzjCWZW9qLuU',
    appId: '1:673634726484:web:88603701cb0ccc54a373c1',
    messagingSenderId: '673634726484',
    projectId: 'todoapp202661',
    authDomain: 'todoapp202661.firebaseapp.com',
    storageBucket: 'todoapp202661.firebasestorage.app',
  );
}
